# Generated by Django 5.2.3 on 2025-06-19 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('receita', '💰 Receita'), ('despesa', '💸 Despesa')], max_length=10)),
                ('categoria', models.CharField(choices=[('alimentacao', '🍔 Alimentação'), ('transporte', '🚗 Transporte'), ('lazer', '🎮 Lazer'), ('saude', '🏥 Saúde'), ('educacao', '📚 Educação'), ('casa', '🏠 Casa'), ('outros', '📦 Outros')], max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
