# Generated by Django 5.2.3 on 2025-06-23 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transacao_options_transacao_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Viagem para Europa', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da meta')),
                ('tipo', models.CharField(choices=[('economia', '💰 Economia'), ('investimento', '📈 Investimento'), ('pagamento', '💳 Pagamento de Dívida'), ('compra', '🛒 Compra Específica')], default='economia', max_length=20)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, help_text='Quanto quer alcançar?', max_digits=12)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, help_text='Quanto já conseguiu', max_digits=12)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_prazo', models.DateField(help_text='Até quando quer alcançar?')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', '🎯 Ativa'), ('pausada', '⏸️ Pausada'), ('concluida', '✅ Concluída'), ('cancelada', '❌ Cancelada')], default='ativa', max_length=20)),
                ('valor_mensal_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notificacoes_ativas', models.BooleanField(default=True)),
                ('conquistas', models.JSONField(blank=True, default=list)),
                ('streak_dias', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
